In [12]:
import torch

In [13]:
a = torch.rand(3,2)

In [14]:
a.unsqueeze_(0).shape

torch.Size([1, 3, 2])

In [15]:
a.repeat_interleave(2,0).shape

torch.Size([2, 3, 2])

In [16]:
a.shape

torch.Size([1, 3, 2])

In [17]:
a

tensor([[[0.7316, 0.2213],
         [0.7069, 0.9400],
         [0.3443, 0.5597]]])

In [18]:
a.narrow(-1,0,1).shape

torch.Size([1, 3, 1])

In [19]:
import torch

x = torch.arange(12).reshape(3, 4)
y = x.narrow(dim=1, start=1, length=2)
x
# y 包含列 1 和 2，对 y 的修改会反映到 x


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [20]:
y.shape
y

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])

In [21]:
a = torch.tensor([[0.2,0,0,0,0.8,0],[0,0.2,0,0,0,0.8]])
b = torch.tensor([[1,2,0,1,-1,3]]).transpose_(1,0).float()

In [22]:
a@b

tensor([[-0.6000],
        [ 2.8000]])