In [1]:
import torch

In [3]:
a = torch.rand(3,2)

In [8]:
a.unsqueeze_(0).shape

torch.Size([1, 3, 2])

In [16]:
a.repeat_interleave(2,0).shape

torch.Size([2, 3, 2])

In [26]:
a.shape

torch.Size([1, 3, 2])

In [25]:
a

tensor([[[0.8578, 0.9133],
         [0.8243, 0.7649],
         [0.6749, 0.7556]]])

In [27]:
a.narrow(-1,0,1).shape

torch.Size([1, 3, 1])

In [31]:
import torch

x = torch.arange(12).reshape(3, 4)
y = x.narrow(dim=1, start=1, length=2)
x
# y 包含列 1 和 2，对 y 的修改会反映到 x


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [32]:
y.shape
y

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])