In [12]:
import torch

In [13]:
a = torch.rand(3,2)

In [14]:
a.unsqueeze_(0).shape

torch.Size([1, 3, 2])

In [15]:
a.repeat_interleave(2,0).shape

torch.Size([2, 3, 2])

In [16]:
a.shape

torch.Size([1, 3, 2])

In [17]:
a

tensor([[[0.3958, 0.3341],
         [0.5275, 0.3575],
         [0.2911, 0.8467]]])

In [18]:
a.narrow(-1,0,1).shape

torch.Size([1, 3, 1])

In [19]:
import torch

x = torch.arange(12).reshape(3, 4)
y = x.narrow(dim=1, start=1, length=2)
x
# y 包含列 1 和 2，对 y 的修改会反映到 x


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [20]:
y.shape
y

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])

In [21]:
import torch

# --------- 和原 numpy 一样的输入 ---------
v1 = torch.tensor([1., 2.])
v2 = torch.tensor([3., 4.])
v3 = torch.tensor([-1., 5.])
alpha = torch.tensor([0.2, 0.3, 0.5])   # weights

# k = 3, d = 2
V_concat = torch.cat([v1, v2, v3])      # shape: (k*d,) = (6,)
d = 2
I = torch.eye(d)                        # shape: (d, d) = (2, 2)

# A 的形状: (d, k*d) = (2, 6)
A = torch.kron(alpha.view(1, -1), I)    # 等价于 np.kron(alpha.reshape(1,-1), I)

# --------- 两种写法的输出 ---------
y_matrix = A @ V_concat                 # 矩阵形式
y_sum = alpha[0]*v1 + alpha[1]*v2 + alpha[2]*v3   # 逐向量加权求和

print("V_concat:", V_concat,"V_concat.shape:",V_concat.shape)
print("A:\n", A,"A.shape:",A.shape)
print("y_matrix:", y_matrix,"y_matrix.shape:",y_matrix.shape)
print("y_sum   :", y_sum)
print("数值是否相同:", torch.allclose(y_matrix, y_sum))


V_concat: tensor([ 1.,  2.,  3.,  4., -1.,  5.]) V_concat.shape: torch.Size([6])
A:
 tensor([[0.2000, 0.0000, 0.3000, 0.0000, 0.5000, 0.0000],
        [0.0000, 0.2000, 0.0000, 0.3000, 0.0000, 0.5000]]) A.shape: torch.Size([2, 6])
y_matrix: tensor([0.6000, 4.1000]) y_matrix.shape: torch.Size([2])
y_sum   : tensor([0.6000, 4.1000])
数值是否相同: True


In [23]:
import einops
q = torch.randn(1024,32,16,512)
k = torch.randn(1024,32,16,512)
v = torch.randn(1024,32,16,512)
q, k, v = (einops.rearrange(t, "s b h d -> b s h d") for t in (q, k, v))
print("q.shape: ",q.shape," k.shape: ",k.shape," v.shape:",v.shape)


q.shape:  torch.Size([32, 1024, 16, 512])  k.shape:  torch.Size([32, 1024, 16, 512])  v.shape: torch.Size([32, 1024, 16, 512])


In [ ]:
x = torch.randn(32,512)
x = einops.rearrange(x, "b (h d) -> b h d", h=8)
print("x.shape:",x.shape)

In [ ]:
x = einops.rearrange(x, "b h d -> b (h d)")
print("x.shape:",x.shape)